INSERT INTO Artisti (IdArtista, Cognome, Nome, Pseudonimo, DataNascita, LuogoNascita, DataMorte, LuogoMorte, Stile, NazioneNascita)
VALUES (1, 'Berti', 'Antonio', 'Non noto', '1904-08-24', 'San Piero a Sieve, Firenze', '1990', 'Sesto Fiorentino, Firenze', 'Scultura figurativa, specializzato in ritratti e monumenti commemorativi', 'Italia');
INSERT INTO Artisti (IdArtista, Cognome, Nome, Pseudonimo, DataNascita, LuogoNascita, DataMorte, LuogoMorte, Stile, NazioneNascita) VALUES (2, 'Prandoni', 'Attilio', NULL, NULL, 'Milano', NULL, NULL, 'Scultura', 'Italia');
INSERT INTO Artisti (IdArtista, Cognome, Nome, Pseudonimo, DataNascita, LuogoNascita, DataMorte, LuogoMorte, Stile, NazioneNascita) VALUES (3, 'Maironi', 'Cesare', NULL, '1824-06-04', 'Valtesse (Bergamo)', '1891-02-24', 'Bergamo', 'Scultura accademica, influenze neoclassiche', 'Italia');
INSERT INTO Artisti (IdArtista, Cognome, Nome, Pseudonimo, DataNascita, LuogoNascita, DataMorte, LuogoMorte, Stile, NazioneNascita) VALUES (4, 'Maironi', 'Alberto', NULL, NULL, 'Probabilmente in Lombardia', NULL, NULL, 'Scultura accademica, influenze neoclassiche', 'Italia');
INSERT INTO Artisti (IdArtista, Cognome, Nome, Pseudonimo, DataNascita, LuogoNascita, DataMorte, LuogoMorte, Stile, NazioneNascita) VALUES (5, 'Gotti', 'Mario', 'Nessuno', '1930', 'Sorisole, Bergamo, Italia', '2017', NULL, 'Pittura paesaggistica e scultura', 'Italiana');
INSERT INTO Artisti (IdArtista, Cognome, Nome, Pseudonimo, DataNascita, LuogoNascita, DataMorte, LuogoMorte, Stile, NazioneNascita) VALUES (6, 'Bazzaro', 'Ernesto', 'NULL', '1859-05-29', 'Milano', '1937-05-18', 'Milano', 'Impressionismo', 'Italia');
INSERT INTO Artisti (IdArtista, Cognome, Nome, Pseudonimo, DataNascita, LuogoNascita, DataMorte, LuogoMorte, Stile, NazioneNascita) VALUES (7, 'Barzaghi', 'Francesco', NULL, '1839-02-10', 'Milano', '1892-08-21', 'Precotto (Milano)', 'Realista', 'Italiana');
INSERT INTO Artisti (IdArtista, Cognome, Nome, Pseudonimo, DataNascita, LuogoNascita, DataMorte, LuogoMorte, Stile, NazioneNascita) VALUES (8, 'Manzoni', 'Giacomo', 'Giacomo Manzù', '1908-12-22', 'Bergamo', '1991-01-17', 'Roma (vicino Ardea)', 'Realismo ed espressionismo, con una forte influenza dell’arte classica', 'Italia');
INSERT INTO Artisti (IdArtista, Cognome, Nome, Pseudonimo, DataNascita, LuogoNascita, DataMorte, LuogoMorte, Stile, NazioneNascita) VALUES (9, 'Siccardi', 'Giuseppe', NULL, '1883-07-18', 'Albino', '1956-02-18', 'Bergamo', 'Realista e figurativo', 'Italia');
INSERT INTO Artisti (IdArtista, Cognome, Nome, Pseudonimo, DataNascita, LuogoNascita, DataMorte, LuogoMorte, Stile, NazioneNascita) VALUES (10, 'Bistolfi', 'Leonardo', 'Poeta della Morte', '1859-03-15', 'Casale Monferrato', '1933-09-03', 'La loggia', 'Simbolismo', 'italiana');
INSERT INTO Artisti (IdArtista, Cognome, Nome, Pseudonimo, DataNascita, LuogoNascita, DataMorte, LuogoMorte, Stile, NazioneNascita) VALUES (11, 'Pagani', 'Luigi', 'Amadio Luigi', '1829-12-19', 'Bergamo', '1905-10-21', 'Milano', 'Classicista, realista', 'italiana');
INSERT INTO Artisti (IdArtista, Cognome, Nome, Pseudonimo, DataNascita, LuogoNascita, DataMorte, LuogoMorte, Stile, NazioneNascita) VALUES (12, 'Marzot', 'Giuseppe', 'Beppe', '1932', 'Vicenza', '2014-04-19', 'Bologna', 'Scultoreo informale', 'Italiana');
INSERT INTO Artisti (IdArtista, Cognome, Nome, Pseudonimo, DataNascita, LuogoNascita, DataMorte, LuogoMorte, Stile, NazioneNascita) VALUES (13, 'Gambirasio', 'Giuseppe', NULL, '1930', 'Bergamo', '2016-10-14', 'Bergamo', 'Architettura sperimentale', 'Italiana');
INSERT INTO Artisti (IdArtista, Cognome, Nome, Pseudonimo, DataNascita, LuogoNascita, DataMorte, LuogoMorte, Stile, NazioneNascita) VALUES (14, 'Jerace', 'Francesco', NULL, '1853-07-26', 'Polistena (Calabria)', '1937-01-18', 'Napoli', 'Neoclassicismo con influenze romantiche e realiste', 'Italia');
INSERT INTO Artisti (IdArtista, Cognome, Nome, Pseudonimo, DataNascita, LuogoNascita, DataMorte, LuogoMorte, Stile, NazioneNascita) VALUES (15, 'Riva', 'Ugo', 'NULL', '1951-08-09', 'Bergamo', NULL, NULL, 'Scultura contemporanea influenzata dall’antico', 'Italia');