services:
  mariadb:
    image: mariadb:latest
    container_name: miradb
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./artisti.sql:/docker-entrypoint-initdb.d/02-artisti.sql
      - ./opere.sql:/docker-entrypoint-initdb.d/03-opere.sql
    restart: unless-stopped